# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

callback1_cpp <- function() {
    invisible(.Call(`_jointprof_callback1_cpp`))
}

callback2_cpp <- function() {
    invisible(.Call(`_jointprof_callback2_cpp`))
}

callback3_cpp <- function() {
    invisible(.Call(`_jointprof_callback3_cpp`))
}

init_profiler_impl <- function() {
    .Call(`_jointprof_init_profiler_impl`)
}

start_profiler_impl <- function(ldc, path) {
    invisible(.Call(`_jointprof_start_profiler_impl`, ldc, path))
}

stop_profiler_impl <- function(ldc) {
    invisible(.Call(`_jointprof_stop_profiler_impl`, ldc))
}

